---
apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "example-nats"
spec:
  size: 3
---
apiVersion: "streaming.nats.io/v1alpha1"
kind: "NatsStreamingCluster"
metadata:
  name: "example-stan"
spec:
  # Number of nodes in the cluster
  size: 3

  # STAN Server to use in the container
  image: "nats-streaming:latest"

  # Service to which STAN Cluster nodes will connect.
  natsSvc: "example-nats"
