apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-streaming-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nats-streaming-operator
  template:
    metadata:
      labels:
        name: nats-streaming-operator
    spec:
      containers:
        - name: nats-streaming-operator
          image: wallyqs/nats-streaming-operator:dev
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - nats-streaming-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "nats-streaming-operator"
